DELETE http://localhost:3003/api/blogs/64c0ee28414a62330793d664
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImpodWxjZXMiLCJpZCI6IjY0YmY5MjlmZTA0YzU0NjgyOTJiMDBkOCIsImlhdCI6MTY5MDM2NTQ2MCwiZXhwIjoxNjkwMzY5MDYwfQ.vf1eMNpggKxvju7CooSdcYEpslOZwNMzP5tKRtSuQ2I